image:https://spring.io/badges/spring-data-gemfire/ga.svg[Spring Data GemFire,link=https://projects.spring.io/spring-data-gemfire#quick-start] image:https://spring.io/badges/spring-data-gemfire/snapshot.svg[Spring Data GemFire,link=https://projects.spring.io/spring-data-gemfire#quick-start]

= Spring Data for Pivotal GemFire image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-gemfire%2Fmain&subject=Build[link=https://jenkins.spring.io/view/SpringData/job/spring-data-gemfire/] https://gitter.im/spring-projects/spring-data[image:https://badges.gitter.im/spring-projects/spring-data.svg[Gitter]]

The primary goal of the Spring Data for Pivotal GemFire project is to make it easier to build highly scalable _Spring_ powered applications using https://pivotal.io/pivotal-gemfire[Pivotal GemFire] as the underlying distributed, in-memory data management platform.

== Features

* XML namespace to https://docs.spring.io/spring-data-gemfire/docs/current/reference/html/#bootstrap[configure and create Pivotal GemFire resources declaratively with Spring]
* Annotation model to https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#bootstrap-annotation-config[quickly and easily get started with Pivotal GemFire out-of-the-box]
* Simplifies https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#apis[working with Pivotal GemFire APIs]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#apis:spring-cache-abstraction[Spring Cache Abstraction backed by Pivotal GemFire]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#mapping[Spring Data Mapping infrastructure applied to POJOs stored in Pivotal GemFire]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#gemfire-repositories[Spring Data Repositories backed by Pivotal GemFire]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#apis:transaction-management[Pivotal GemFire Cache Transactions through Spring's Declarative Transaction Management]
* Additional support for https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#apis:global-transaction-management[using Pivotal GemFire in Global, JTA Transactions through Spring's Declarative Transaction Management]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#serialization[Enhanced support for Pivotal GemFire Serialization]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#function-annotations[Annotations for Function Executions]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#apis:continuous-query[Support for Continuous Query]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#bootstrap:lucene[Enhanced support for Apache Lucene Integration]
* https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#gemfire-bootstrap[Bootstrapping a Spring Context with Pivotal GemFire]
* Spring Tool Suite https://docs.spring.io/sts/nan/v310/NewAndNoteworthy.html[Spring Project Templates for Pivotal GemFire]

== Code of Conduct

This project is governed by the link:CODE_OF_CONDUCT.adoc[Spring Code of Conduct]. By participating, you are expected to uphold this code of conduct. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Getting Started

Here is a quick teaser of an application using Spring Data Repositories in Java:

[source,java]
----
public interface PersonRepository extends CrudRepository<Person, Long> {

  List<Person> findByLastname(String lastname);

  List<Person> findByFirstnameLike(String firstname);
}

@Service
public class MyService {

  private final PersonRepository repository;

  public MyService(PersonRepository repository) {
    this.repository = repository;
  }

  public void doWork() {

    repository.deleteAll();

    Person person = new Person();
    person.setFirstname("John");
    person.setLastname("Blum");
    repository.save(person);

    List<Person> lastNameResults = repository.findByLastname("Blum");
    List<Person> firstNameResults = repository.findByFirstnameLike("J*");
 }
}
----

Configure a Pivotal GemFire cache and Region (REPLICATE, PARTITION and so on):

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:gfe="http://www.springframework.org/schema/gemfire"
	xmlns:gfe-data="http://www.springframework.org/schema/data/gemfire"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance
  xsi:schemaLocation="
    http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/geode https://www.springframework.org/schema/gemfire/spring-gemfire.xsd
	http://www.springframework.org/schema/data/gemfire https://www.springframework.org/schema/data/geode/spring-data-gemfire.xsd">

  <gfe:cache/>

  <gfe:partitioned-region id="ExampleRegion" copies="2">

  <bean id="gemfireTemplate" class="org.springframework.data.gemfire.GemfireTemplate" p:region-ref="ExampleRegion"/>
	<gfe-data:repositories base-package="com.acme"/>
</beans>
----

=== Maven configuration

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-gemfire</artifactId>
  <version>${version}.RELEASE</version>
</dependency>
----

If you'd rather like the latest snapshots of the upcoming major version, use our Maven snapshot repository and declare the appropriate dependency version.

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-gemfire</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>https://repo.spring.io/libs-snapshot</url>
</repository>
----

== Getting Help

Having trouble with Spring Data? We’d love to help!

* Check the
https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/[reference documentation], and https://docs.spring.io/spring-data/gemfire/docs/current/api/[Javadocs].
* Learn the Spring basics – Spring Data builds on Spring Framework, check the https://spring.io[spring.io] web-site for a wealth of reference documentation.
If you are just starting out with Spring, try one of the https://spring.io/guides[guides].
* If you are upgrading, check out the https://docs.spring.io/spring-data/gemfire/docs/current/changelog.txt[changelog] for "`new and noteworthy`" features.
* Ask a question - we monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with https://stackoverflow.com/tags/spring-data[`spring-data-gemfire`].
You can also chat with the community on https://gitter.im/spring-projects/spring-data[Gitter].
* Report bugs with Spring Data for Pivotal GemFire at https://jira.spring.io/browse/SGF[jira.spring.io/browse/SGF].

== Reporting Issues

Spring Data uses JIRA as issue tracking system to record bugs and feature requests. If you want to raise an issue, please follow the recommendations below:

* Before you log a bug, please search the
https://jira.spring.io/browse/SGF[issue tracker] to see if someone has already reported the problem.
* If the issue doesn’t already exist, https://jira.spring.io/browse/SGF[create a new issue].
* Please provide as much information as possible with the issue report, we like to know the version of Spring Data that you are using and JVM version.
* If you need to paste code, or include a stack trace use JIRA `{code}…{code}` escapes before and after your text.
* If possible try to create a test-case or project that replicates the issue. Attach a link to your code or a compressed file containing your code.

== Building from Source

You don’t need to build from source to use Spring Data (binaries in https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and greatest, Spring Data can be easily built with the https://github.com/takari/maven-wrapper[maven wrapper].
You also need JDK 1.8.

[source,bash]
----
 $ ./mvnw clean install
----

If you want to build with the regular `mvn` command, you will need https://maven.apache.org/run-maven/index.html[Maven v3.5.0 or above].

_Also see link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] if you wish to submit pull requests, and in particular please sign the https://cla.pivotal.io/sign/spring[Contributor’s Agreement] before your first non-trivial change._

=== Building reference documentation

Building the documentation builds also the project without running tests.

[source,bash]
----
 $ ./mvnw clean install -Pdistribute
----

The generated documentation is available from `target/site/reference/html/index.html`.

== Examples

For examples on using the _Spring Data for Pivotal GemFire_, see the https://github.com/SpringSource/spring-gemfire-examples[spring-gemfire-examples] project.


== License

Spring Data for Pivotal GemFire is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
