[[data-access]]
= Using the Data Access Namespace

In addition to the core XML namespace (`gfe`), Spring Data for Pivotal GemFire provides a data access XML namespace (`gfe-data`),
which is primarily intended to simplify the development of Pivotal GemFire client applications. This namespace currently contains
support for Pivotal GemFire <<gemfire-repositories, Repositories>> and function <<function-execution, execution>>,
as well as a `<datasource>` tag that offers a convenient way to connect to a Pivotal GemFire cluster.

[[data-access:datasource]]
== An Easy Way to Connect to Pivotal GemFire

For many applications, a basic connection to a Pivotal GemFire data grid using default values is sufficient.
Spring Data for Pivotal GemFire's `<datasource>` tag provides a simple way to access data. The data source creates
a `ClientCache` and connection `Pool`. In addition, it queries the cluster servers for all existing root Regions
and creates an (empty) client Region proxy for each one.

[source,xml]
----
<gfe-data:datasource>
  <locator host="remotehost" port="1234"/>
</gfe-data:datasource>
----

The `<datasource>` tag is syntactically similar to `<gfe:pool>`. It may be configured with one or more nested `locator`
or `server` tags to connect to an existing data grid. Additionally, all attributes available to configure a pool
are supported. This configuration automatically creates client region beans for each region defined on
cluster members connected to the locator, so they can be seamlessly referenced by Spring Data mapping annotations
(`GemfireTemplate`) and wired into application classes.

Of course, you can explicitly configure client regions. For example, if you want to cache data in local memory, as the following example shows:

[source,xml]
----
<gfe-data:datasource>
  <locator host="remotehost" port="1234"/>
</gfe-data:datasource>

<gfe:client-region id="Example" shortcut="CACHING_PROXY"/>
----
