[[bootstrap:diskstore]]
= Configuring a DiskStore

As of Release 1.2.0, _Spring Data GemFire_ supports `DiskStore` configuration via the `disk-store` element.

NOTE: Prior to Release 1.2.0, `disk-store` was a child element of the `\*-region` elements.
If you have Regions configured with disk storage using a prior release of _Spring Data GemFire_
and want to upgrade to the latest release, move all `disk-store` element(s) to the top-level,
assign an `id` and use the `*-region` element's `disk-store-ref` attribute.

Also, `disk-synchronous` is now a `*-region` attribute.

[source,xml]
----
<gfe:disk-store id="diskStore1" queue-size="50" auto-compact="true"
        max-oplog-size="10" time-interval="9999">
        <gfe:disk-dir location="/gemfire/store1/" max-size="20"/>
        <gfe:disk-dir location="/gemfire/store2/" max-size="20"/>
</gfe:disk-store>
----

`DiskStores` are used by Regions for file system persistent backup or overflow storage of evicted entries,
and persistent backup of WAN Gateways.  Multiple components may share the same `DiskStore`.
Additionally, multiple directories may be defined for a single `DiskStore`.

Please refer to Pivotal GemFire's documentation for an explanation of the configuration options.
