[[ref-introduction]]
= Document Structure

The following chapters explain the core functionality offered by _Spring Data GemFire_ for Pivotal GemFire.

<<bootstrap>> describes the configuration support provided for bootstrapping, configuring, initializing
and accessing Pivotal GemFire Caches, Regions, and related Distributed System components.

<<apis>> explains the integration between the Pivotal GemFire APIs and the various data access features
available in _Spring_, such as transaction management and exception translation.

<<serialization>> describes the enhancements for Pivotal GemFire (de)serialization and management of associated objects.

<<mapping>> describes persistence mapping for POJOs stored in Pivotal GemFire using _Spring Data_.

<<gemfire-repositories>> describes how to create and use _Spring Data Repositories_ to access data in Pivotal GemFire.

<<function-annotations>> describes how to create and use Pivotal GemFire Functions using Annotations.

<<gemfire-bootstrap>> describes how to bootstrap a _Spring_ `ApplicationContext` running in an Pivotal GemFire server
using _Gfsh_.

<<samples>> describes the examples provided with the distribution to illustrate the various features
available in _Spring Data GemFire_.
