[[ref-introduction]]
= Document Structure

The following chapters explain the core functionality offered by _Spring Data Geode_ for Apache Geode.

<<bootstrap>> describes the configuration support provided for bootstrapping, configuring, initializing
and accessing Apache Geode Caches, Regions, and related Distributed System components.

<<apis>> explains the integration between the Apache Geode APIs and the various data access features
available in _Spring_, such as transaction management and exception translation.

<<serialization>> describes the enhancements for Apache Geode (de)serialization and management of associated objects.

<<mapping>> describes persistence mapping for POJOs stored in Apache Geode using _Spring Data_.

<<gemfire-repositories>> describes how to create and use _Spring Data Repositories_ to access data in Apache Geode.

<<function-annotations>> describes how to create and use Apache Geode Functions using Annotations.

<<gemfire-bootstrap>> describes how to bootstrap a _Spring_ `ApplicationContext` running in an Apache Geode server
using _Gfsh_.

<<samples>> describes the examples provided with the distribution to illustrate the various features
available in _Spring Data Geode_.
