[[ref-introduction]]
= Document Structure

The following chapters explain the core functionality offered by Spring Data for Pivotal GemFire:

* <<bootstrap>> describes the configuration support provided for configuring, initializing, and accessing
Pivotal GemFire caches, regions, and related distributed system components.

* <<apis>> explains the integration between the Pivotal GemFire APIs and the various data access features
available in Spring, such as data access, exception translation, transaction management, and caching.

* <<serialization>> describes enhancements to Pivotal GemFire's serialization and deserialization of managed objects.

* <<mapping>> describes persistence mapping for POJOs stored in Pivotal GemFire using Spring Data.

* <<gemfire-repositories>> describes how to create and use Spring Data Repositories to access data
stored in Pivotal GemFire by using basic CRUD and simple query operations.

* <<function-annotations>> describes how to create and use Pivotal GemFire functions by using annotations
to perform distributed computations where the data lives.

* <<apis:continuous-query>> describes how to use Pivotal GemFire's Continuous Query (CQ) functionality
to process a stream of events based on interest defined and registered using a Pivotal GemFire OQL (Object Query Language) query.

* <<gemfire-bootstrap>> describes how to bootstrap a Spring `ApplicationContext` running in an Pivotal GemFire server
by using `Gfsh`.

* <<samples>> describes the examples provided with the distribution to illustrate the various features
available in Spring Data for Pivotal GemFire.
