[[ref-introduction]]
= Document Structure

The following chapters explain the core functionality offered by _Spring Data for Pivotal GemFire_.

<<bootstrap>> describes the configuration support provided for configuring, initializing and accessing
Pivotal GemFire Caches, Regions, and other related Distributed System components.

<<apis>> explains the integration between the Pivotal GemFire APIs and the various data access features
available in _Spring_, such as data access, exception translation, transaction management and caching.

<<serialization>> describes enhancements to Pivotal GemFire's (de)serialization of managed objects.

<<mapping>> describes persistence mapping for POJOs stored in Pivotal GemFire using _Spring Data_.

<<gemfire-repositories>> describes how to create and use _Spring Data Repositories_ to access data
stored in Pivotal GemFire using basic CRUD and simple query operations.

<<function-annotations>> describes how to create and use Pivotal GemFire Functions using Annotations
to perform distributed computations where the data lives.

<<apis:continuous-query>> describes how to use Pivotal GemFire's Continuous Query (CQ) functionality
to process a stream of events based on interest defined and registered using a Pivotal GemFire OQL query.

<<gemfire-bootstrap>> describes how to bootstrap a _Spring_ `ApplicationContext` running in an Pivotal GemFire server
using _Gfsh_.

<<samples>> describes the examples provided with the distribution to illustrate the various features
available in _Spring Data for Pivotal GemFire_.
