[[ref-introduction]]
= Document Structure

The following chapters explain the core functionality offered by {sdg-name}:

* <<bootstrap>> describes the configuration support provided for configuring, initializing, and accessing
{data-store-name} Caches, Regions, and related distributed system components.

* <<apis>> explains the integration between the {data-store-name} APIs and the various data access features
available in Spring, such as template-based data access, exception translation, transaction management, and caching.

* <<serialization>> describes enhancements to {data-store-name}'s serialization and deserialization of managed objects.

* <<mapping>> describes persistence mapping for POJOs stored in {data-store-name} using Spring Data.

* <<gemfire-repositories>> describes how to create and use Spring Data Repositories to access data
stored in {data-store-name} by using basic CRUD and simple query operations.

* <<function-annotations>> describes how to create and use {data-store-name} Functions by using annotations
to perform distributed computations where the data lives.

* <<apis:continuous-query>> describes how to use {data-store-name}'s Continuous Query (CQ) functionality
to process a stream of events based on interest that is defined and registered with {data-store-name}'s
OQL (Object Query Language).

* <<gemfire-bootstrap>> describes how to configure and bootstrap a Spring `ApplicationContext`
running in an {data-store-name} server using `Gfsh`.

* <<samples>> describes the examples provided with the distribution to illustrate the various features
available in {sdg-name}.
