/*
 * Copyright 2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.data.gemfire.repository.query;

/**
 * Interface to enable callback/override the generated OQL query Sample usecase is to override region-name to facilitate
 * switching region-name dynamically
 *
 * @see SGF-713 for details Created by jebuselwyn.martin on 1/20/2018.
 *
 * @author jebuselwyn.martin
 */
public interface QueryCustomizer {

	/**
	 * Extension point to customize query generated by StringBasedGemfireRepo Sample usecase: If there are needs to
	 * override the region-name at runtime to connect based on environment or based on user-specific snapshots, this
	 * extension point can be leveraged The Client application should provide the GemfireFactory and supply the right
	 * Impl. The impl of the QueryCustomizer should be wired through constructor-injection
	 *
	 * @param queryString
	 * @return
	 */
	QueryString customizeQuery(QueryString queryString);

}
